### ISSUE TITLE
`npm run dev` not working

### ISSUE THREAD

**Issue by johannesschrott** [oliverfindl/electron-vue-boilerplate#2]
When I run `npm run dev` a webpack development server is launched, but nothing is displayed. As I am quite new to this whole subject I am unsure if this is a bug or if I am doingsomething wrong.

**Comment by oliverfindl** [comment]
Hello,

you need to open it in electron app with `npm run start` to see your [Vue@3](https://github.com/vuejs/vue-next) app. It won't work in browser, because it uses [node bindings](https://webpack.js.org/configuration/node/) (you can remove them from webpack config, but you won't be able to use some features).

So, in short, you need to run `npm run dev` in one terminal to launch "website" and `npm run start` in second terminal to launch electron app that loads this "website".

Please let me know if this helps.

Thanks

**Comment by johannesschrott** [comment]
Thank you for your quick answer 👍  Now I got it up and running.
