### ISSUE TITLE
How can I obfuscate the production VueJS code?

### ISSUE THREAD

**Issue by hayr-hotoca** [oliverfindl/electron-vue-boilerplate#9]
The production is minified but can we obfuscate it?

I am trying to add https://github.com/javascript-obfuscator/webpack-obfuscator to the webpack-vue-app.config.js file but it only breaks the code and the app stops working.

**Comment by oliverfindl** [comment]
Hello,

any obfuscator for web apps should work with this boilerplate. Electron part of it is only serving your built [Vue](https://github.com/vuejs/vue-next) app in similar fashion as is web server. I personally don't know, where lies your problem, but you can try just to serve yours built app and see, if this works. If not, there is some issue with obfuscator or your configuration. And if you are using some of Electron APIs inside your [Vue](https://github.com/vuejs/vue-next) app, that might break obfuscators, because they most probably won't know Electron APIs and they might or might not try to obfuscate them.

If you have any more questions, feel free to ask here.

Thanks.
